---
title: "La COVID-19 a-t-elle eu un impact sur les schémas de mobilité résidentielle des migrants en Suisse ?"
Author: "Hategekimana V. & Wanner P."
format: revealjs
---

## Introduction

- La Covid-19 a eu un impact majeur sur la mobilité
  - Confinement + Arrêt de travail
    - Réflexion sur la vie du ménage
  - Limitation de la mobilité internationale
  - Changement de la mobilité interne
    - Mobilité hors des villes

**Cette étude se concentre sur le comportement de mobilité des étrangers nouvellement arrivés en Suisse.**

## Contexte Suisse

La Suisse c'est:

- Forte proportion d'étrangers
  - Travail et Réunion familiale principalement
  - Niveau d'éducation élevé
  - Arriver dans les centres économiques/urbains
    - Attraction du travail
- La Suisse est un pays de locataires (61% en 2022: OFS)

**Très intéressant pour étudier l'impact de la COVID-19 sur la mobilité résidentielle**
  

## Hypothèses

Nous allons tester deux facteurs principaux:

(1) **Les taux de mobilité varient en fonction des différentes cohortes**:
    - Cohort pré-covid (2015, 2017)
    - Cohorte covid (2019)
(2) **La mobilité varie en fonction du niveau d'urbanité**
    - Mobilité supérieur dans les villes
    - Mobilité inférieur dans les milieux ruraux ou périphériques

## Mobilité résidentielle
### Facteurs influençant la mobilité résidentielle

- **Conditions économiques** (revenus, coûts du logement, situation professionnelle, crises)
  - (Rérat, 2016 ; Wanner, 2017)
- **Événements familiaux** (naissance, mariage, divorce)
- **Réseaux sociaux** (contacts locaux, réseaux personnels)
- **Contexte géographique** (type de région, espace disponible)
- **Condition psychologique** (Rôle du logement, Ancrage)

::: {.notes}

## Le rôle des conditions économiques
Les ménages à faibles revenus et les locataires sont particulièrement sensibles aux déterminants économiques.

## Les événements familiaux comme catalyseurs de la mobilité
Les événements familiaux peuvent déclencher des déménagements, dont le moment et l'intensité dépendent de facteurs individuels

- Naissance d'un enfant
- Mariage
- Divorce
- Le moment et l'intensité des déménagements sont influencés par le revenu, la composition du ménage et le contexte culturel.

## Réseaux sociaux et dispersion spatiale
Des contacts locaux solides réduisent les coûts de déménagement, tandis que la mobilité entraîne une dispersion spatiale et un remodelage des structures de soutien social.

### Réseaux sociaux et dispersion spatiale

- Des contacts locaux forts réduisent les coûts de déplacement
- La mobilité entraîne une dispersion spatiale au sein des réseaux personnels
La mobilité entraîne une dispersion spatiale au sein des réseaux personnels - Remodelage des structures de soutien social et augmentation de la transitivité au sein de celles-ci


## Dimensions psychologiques de la mobilité
Les sentiments anticipés de solitude et de tristesse motivent l'élargissement des réseaux sociaux.

### Dimensions psychologiques de la mobilité

- Sentiments anticipés de solitude et de tristesse
- Les sentiments de solitude et de tristesse anticipés motivent l'élargissement des réseaux sociaux
- Le type et la distance de la relocalisation influencent les réponses psychologiques.

## Complexité des choix de mobilité résidentielle
Les modèles de mobilité résultent de compromis complexes entre de multiples facteurs.

### Complexité des choix de mobilité résidentielle

Les choix de mobilité résidentielle sont influencés par une série de facteurs, notamment les préférences en matière de logement, les contraintes économiques, les liens sociaux, les événements familiaux et les facteurs géographiques. Comprendre cette complexité est essentiel pour comprendre les réponses individuelles à des circonstances difficiles.

:::

## COVID-19

- Augmentation de la mobilité résidentielle hors des centres-villes
  - Marginal en Suisse
- Augmentation de la considération du confort des logements

**En Suisse:**

- Confinement léger
- Chômage partiel: protection des emplois
  - Faible impact économique individuel

## Population urbaine en Suisse

- Migration contribue à la croissance
- Jeunes adultes
- Ménages à revenus moyens ou élevés
- Ménages non familiaux 

(Beckers & Boschman, 2019 ; Rérat, 2016, 2019; Tippel et al., 2017)

## Intégration et centralité urbaine

- Les résidents étrangers sont d'abord attirés par les grands ou moyens centres urbains, puis se déplacent
  - Opportunités d'emploi
- Un séjour plus long diminue la propension à la migration interne.

(Bayona-Carrasco & Gil-Alonso, 2012 ; Neville, 1994).

## Dynamique interne de la migration des résidents étrangers

- L'enseignement supérieur et les qualifications professionnelles conduisent à s'éloigner des centres urbains (Beckers & Boschman, 2019 ; M. Boyd, 1989 ; etc.).
  - Les conditions de logement (Hansen & Aner, 2017 ; Muhyi & Adianto, 2021).
- Les résidents étrangers **moins qualifiés** restent dans les villes en raison des opportunités d'emploi et des réseaux sociaux (Lerch & Wanner, 2010).

## Ancrage (Anchoring)

**La raison d'immigration est importante!**

**Ancrage:** Les points d'appui et de référence spécifiques qui permettent aux personnes mobiles d'atteindre un certain degré de stabilité et de sécurité psychosocial.

  - Raison d'immigration (Emploi, regroupement familial, études)

## Hypothèses 

- **H1** : Le premier déménagement interne après la migration se produira plus rapidement pour la cohorte COVID-19 (2019 - 2021). 
- **H2a** : Les personnes s'installant dans les centres afficheront une mobilité post-migratoire plus rapide et plus importante que celles qui s'installent dans les régions périphériques.
- **H2b** : La Covid-19 (cohorte 2019) va accentuer cet effet.
- **H3** : Les personnes venues en Suisse pour le travail sont plus mobiles que celles venues pour des raisons familiales, tandis que celles venues pour l'éducation se situent entre les deux.

## Données

- En utilisant des données appariées provenant de **registres administratifs** suisses (Steiner & Wanner, 2015).
  - **Registre des comptes individuels** pour les informations sur les revenus
  - Données du **registre** pour les informations socio-économiques

## Population

- Personnes âgées de 20 à 64 ans, ayant séjourné au moins une année en Suisse et dont la mobilité n'est pas limitée par leur permis de séjour.
- Définie comme les personnes ayant un permis de séjour valable au moins un an (permis L, B et C).
- Exclus les demandeurs d'asile (réfugiés N, F et F), mais inclus les membres de la famille qui rejoignent les réfugiés reconnus avec un permis B.

## Cohortes et cantons

### Focus sur trois cantons suisses et les cohortes de migrants récents

- Genève, Vaud et Zurich : principaux points d'arrivée des immigrants
- Trois cohortes de résidents permanents étrangers qui se sont récemment installés en Suisse (2015, 2017 et 2019)
- 3 ans (1095 jours)

## Modèle statistique

- Modèle de hasard proportionnel de Cox
  - Variable dépendante: premier déménagement interne (changement de commune).
  - La variable temporelle:
    - Jours (max. 1095 = 3 ans)
    - Censurée à droite, car:
      - Événements concurrents (décès, mobilité internationale)
      - Fin de la période d'observation

$$
h(t) = h_0(t) \exp(\beta_1 \times \text{Y2017} + \beta_2 \times \text{Y2019} + \beta_3 \times \text{ImmigrationReason} + \beta_4 \times \text{LevelOfUrbanity} + \sum_{i=5}^{13} \beta_i \times \text{Control}_{i-4})
$$

## Trois modèles
Chaque modèle ajoute une couche de profondeur à notre compréhension :

- **Modèle 1** : covariables primaires d'intérêt, y compris le lieu d'arrivée et le groupe de cohorte.
- **Modèle 2** : ajoute une variable de médiation (**raison de l'immigration**) pour tester l'effet sur le résultat de la mobilité.
- **Modèle 3** : introduis des effets d'**interaction** entre les variables **géographiques** et les caractéristiques de la **cohorte**.

## Variables (1)

(image)

## Variables (2)

- Année d'arrivée (2015, 2017, 2019)
- Niveau d'urbanité (commune centre de l'agglomération, autre commune urbaine, zone intermédiaire, commune rurale)
- Raison de l'immigration (regroupement familial, études, activité économique, autres raisons)
- Groupe d'âge (20-39, 40-64)
- Sexe (hommes, femmes)
- Nationalité (pays frontaliers, pays de l'UE/AELE, pays non membres de l'UE/AELE)
- Type de permis (catégorie de référence annuelle) à court terme
- Canton d'arrivée (Genève, Zurich, Vaud)
- Revenu équivalent (quintiles Q1 à Q5)

## Variables dépendantes du temps 

- état civil (célibataire, marié/partenaire, divorcé/veuf)
- Taille du ménage (1 personne, 2-3 personnes, 4-5 personnes, 6-10 personnes)
- Changement de la taille du ménage

## Vérification des l'hypothèses (1)

H1 (Validée):


- La cohorte 2019 se déplace le plus rapidement, suivie par les cohortes 2017 et 2015.

## Vérification des hypothèses (2)

H2a (rejetée):

- Relation inverse: 
  - Les personnes vivant dans des zones intermédiaires ou rurales présentent une mobilité plus rapide.


## Vérification des hypothèses (3)

H2b (effet contraire)

- La Covid-19 accentue l'effet, mais la relation inverse est maintenue

## Vérification des hypothèses (4)

H3 (validée)

- Ordre similaire à nos attentes: 
  - regroupement familial, activité économique, « autres raisons » et études.


## Conclusion (1)
### Discussion

- Les personnes arrivées en Suisse avant Covid-19 (cohorte 2019) avaient des taux de mobilité plus élevés que celles des années précédentes
  - **Suggestion**: davantage investi dans la recherche d'un cadre de vie adéquat.
- La mobilité dans les milieux urbains a été plus faible que dans les périphéries.
  - **Invitation**: Changer l’accent sur les milieux ruraux et s'intéresser à la destination.

## Conclusion (2)
### Discussion

- La raison d'immigration a eu l'effet attendu.
  - **Inattendu**: Mobilité étudiante supérieure à la mobilité des travailleurs.

### Limites

- Hypothèse de risque proportionnelle violée
- Manque de variables plus riches (qualification, période d'arrivée)
  
## Merci pour votre attention

Posez-moi vos questions